apiVersion: v1
kind: Service
metadata:
  name: build-rms-service
spec:
  type: LoadBalancer
  selector:
    app: build-rms
  ports:
  - protocol: TCP
    port: 8050        # External port accessible by users
    targetPort: 5050  # Port inside the container
