apiVersion: v1
kind: Service
metadata:
  name: build-rms-service
spec:
  type: LoadBalancer
  selector:
    app: build-rms
  ports:
  - name: app
    protocol: TCP
    port: 8050
    targetPort: 5050
  - name: pm2-web
    protocol: TCP
    port: 9615        # PM2 web interface external port
    targetPort: 9615  # PM2 web interface container port